[versions]
kotlin = "1.9.25"
tschuchortdev = "1.6.0"
kotest = "5.9.1"
mockk = "1.13.17"
kotestRunnerJunit5Jvm = "5.9.1"
ktlint = "12.2.0"
vanniktech="0.31.0"

[libraries]
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}

tschuchortdev-testing-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "tschuchortdev"}

kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotestRunnerJunit5Jvm" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
